### ISSUE TITLE
Error: can only concatenate str (not "NoneType") to str ...  and UI hanging

### ISSUE THREAD

**Issue by jhergeth** [weaviate/Verba#109]
Hello,

i "successfully" set up a local installation with starting with your docker-compose. I added a local litellm-container to connect to my local ollama setup.
Verba seems to work, but I always get this error:
`WebSocket Error: can only concatenate str (not "NoneType") to str`

The console log around that error is:
```
verba-verba-1         | ERROR:    Exception in ASGI application
verba-verba-1         | Traceback (most recent call last):
verba-verba-1         |   File "/Verba/goldenverba/server/api.py", line 599, in websocket_generate_stream
verba-verba-1         |     async for chunk in manager.generate_stream_answer(
verba-verba-1         |   File "/Verba/goldenverba/verba_manager.py", line 616, in generate_stream_answer
verba-verba-1         |     full_text += result["message"]
verba-verba-1         | TypeError: can only concatenate str (not "NoneType") to str
verba-verba-1         | 
verba-verba-1         | During handling of the above exception, another exception occurred:
verba-verba-1         | 
verba-verba-1         | Traceback (most recent call last):
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
verba-verba-1         |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
verba-verba-1         |     return await self.app(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
verba-verba-1         |     await super().__call__(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
verba-verba-1         |     await self.middleware_stack(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
verba-verba-1         |     await self.app(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
verba-verba-1         |     await self.app(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
verba-verba-1         |     raise exc
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
verba-verba-1         |     await self.app(scope, receive, sender)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
verba-verba-1         |     raise e
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
verba-verba-1         |     await self.app(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
verba-verba-1         |     await route.handle(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
verba-verba-1         |     await self.app(scope, receive, send)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
verba-verba-1         |     await func(session)
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 324, in app
verba-verba-1         |     await dependant.call(**values)
verba-verba-1         |   File "/Verba/goldenverba/server/api.py", line 613, in websocket_generate_stream
verba-verba-1         |     await websocket.send_json(
verba-verba-1         |   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 171, in send_json
verba-verba-1         |     text = json.dumps(data, separators=(",", ":"))
verba-verba-1         |   File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
verba-verba-1         |     **kw).encode(obj)
verba-verba-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
verba-verba-1         |     chunks = self.iterencode(o, _one_shot=True)
verba-verba-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
verba-verba-1         |     return _iterencode(o, 0)
verba-verba-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
verba-verba-1         |     raise TypeError(f'Object of type {o.__class__.__name__} '
verba-verba-1         | TypeError: Object of type TypeError is not JSON serializable
verba-verba-1         | INFO:     connection closed
verba-verba-1         | ✘ WebSocket Error: can only concatenate str (not "NoneType") to str

```

Any suggestions?

**Comment by thomashacker** [comment]
Thanks for the issue, we'll look into that!

**Comment by thomashacker** [comment]
It seems like the token received by your LiteLLM implementation is a NoneType, which is causing the error of appending it to the message string. You can try out the newest Ollama integration to see if this works for you
