### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by erinCodes3276** [weaviate/Verba#122]
When running the command "Verba start" I receive warnings and one TypeError:
2024-03-07 20:05:22.044672: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.9/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/verba", line 5, in <module>
    from goldenverba.server.cli import cli
  File "/usr/local/lib/python3.9/site-packages/goldenverba/server/cli.py", line 6, in <module>
    from goldenverba.verba_manager import VerbaManager
  File "/usr/local/lib/python3.9/site-packages/goldenverba/verba_manager.py", line 29, in <module>
    class VerbaManager:
  File "/usr/local/lib/python3.9/site-packages/goldenverba/verba_manager.py", line 156, in VerbaManager
    def setup_client(self) -> Client | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by thomashacker** [comment]
Thanks for the issue! We'll look into fixing it

**Comment by thomashacker** [comment]
Should be fixed with the latest release
