### ISSUE TITLE
Error: Windows is not supported with EmbeddedDB

### ISSUE THREAD

**Issue by yinhuaicao** [weaviate/Verba#149]
I am trying to get started on win10 and pip. The python version is 3.10.14 and I would like to connect with Azure OpenAI API.
When executing "verba start" command, an exception is raised: Windows is not supported with EmbeddedDB. And the error message points to another link https://github.com/weaviate/weaviate-python-client/issues/239, which indicates that currently weaviate-python-client does not support windows so far.

Is there any other way to run on win10?

Here is error message:

DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  warnings.warn(
⚠ No module named 'torch'
ℹ Setting up client
ℹ Using Weaviate Embedded
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\users\cao7szh\verba\goldenverba\server\api.py", line 33, in <module>
    manager = verba_manager.VerbaManager()
  File "c:\users\cao7szh\verba\goldenverba\verba_manager.py", line 41, in __init__
    self.client = self.setup_client()
  File "c:\users\cao7szh\verba\goldenverba\verba_manager.py", line 229, in setup_client
    client = weaviate.Client(
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\weaviate\client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\weaviate\client.py", line 287, in __parse_url_and_embedded_db
    embedded_db = EmbeddedDB(options=embedded_options)
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\weaviate\embedded.py", line 52, in __init__
    self.check_supported_platform()
  File "C:\Users\CAO7SZH\.conda\envs\rag_llm\lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239
sys:1: ResourceWarning: unclosed <socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8000)>

**Comment by thomashacker** [comment]
Thanks for the issue! We're working on Windows Support for the next Weaviate version. Here are two workarounds you can try:

1. Create a Sandbox Cluster (free, 14 days) on WCS (https://console.weaviate.cloud/) and add these environment variables to your `.env` file:

```bash

WEAVIATE_URL_VERBA=
WEAVIATE_API_KEY_VERBA=

```

2. Use the Docker deployment

```bash

docker compose --env-file .env up -d

```

**Comment by huzaifa0505** [comment]
PS D:\projects\Verba Project\Verba> verba start
INFO:     Will watch for changes in these directories: ['D:\\projects\\Verba Project\\Verba']
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12640] using WatchFiles
lora 
barwa
ℹ Setting up client
ℹ Using Weaviate Embedded
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "d:\projects\verba project\verba\goldenverba\server\api.py", line 37, in <module>
    manager = verba_manager.VerbaManager()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 45, in __init__
    self.client = self.setup_client()
                  ^^^^^^^^^^^^^^^^^^^
  File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 209, in setup_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\weaviate\client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\weaviate\client.py", line 287, in __parse_url_and_embedded_db
    embedded_db = EmbeddedDB(options=embedded_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\weaviate\embedded.py", line 52, in __init__
    self.check_supported_platform()
  File "C:\Users\User\anaconda3\Lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239
having this issue..can you plz tell me how to correct it?
