### ISSUE TITLE
Windows is not supported with EmbeddedDB. plz give solution for it because its not working even after WCS implementation

### ISSUE THREAD

**Issue by huzaifa0505** [weaviate/Verba#180]
I'm encountering an error when trying to run Weaviate with the EmbeddedDB option on a Windows system. The error message indicates that Windows is not currently supported for this functionality.
i have created a environment
installed all the requirements
then setup a llama 3 model 
after that when i am starting the verba, i am facing the issue of embeddingDB, for the solution i have created a sandbox cluster on WCS and copied the URL and API from there and then repeat the whole process but still facing the face issue of embedding

i have also provided the error below, Please can anyone help to resolve this issue

INFO:     Will watch for changes in these directories: ['D:\\projects\\Verba Project\\Verba']
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12028] using WatchFiles
lora 
barwa
ℹ Setting up client
ℹ Using Weaviate Embedded
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "d:\projects\verba project\verba\goldenverba\server\api.py", line 37, in <module>
    manager = verba_manager.VerbaManager()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 45, in __init__
    self.client = self.setup_client()
                  ^^^^^^^^^^^^^^^^^^^
  File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 209, in setup_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\client.py", line 287, in __parse_url_and_embedded_db
    embedded_db = EmbeddedDB(options=embedded_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\embedded.py", line 52, in __init__
    self.check_supported_platform()
  File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by thomashacker** [comment]
It seems like Verba isn't detecting your `.env` files with the Weaviate URL and API Key variable. You can make sure that your current environment has all variables by using `source .env`. Let me know if this helps!

**Comment by huzaifa0505** [comment]
done thank you sir

**Comment by ahsan0444** [comment]
Hi @thomashacker 
Could you pls share what env variables we have to set in the .env file to resolve this error?
Currently I have these two values in my .env file
```
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3
```

And I am running verba on a virtual env on windows using the command
`verba start`
