### ISSUE TITLE
Verba start process fails in the end

### ISSUE THREAD

**Issue by pavlosidelov** [weaviate/Verba#192]
All instalation goes tormaly
verba start command initiated normally but then failed with the next error codes.
---
✔ Connected to Weaviate
ℹ CUDA is available. Using CUDA...
ℹ Setting up components
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/dev/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/server/api.py", line 38, in <module>
    setup_managers(manager)
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/server/util.py", line 13, in setup_managers
    config = load_config(manager)
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/server/util.py", line 227, in load_config
    return get_config(manager)
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/server/util.py", line 40, in get_config
    "components": {
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/server/util.py", line 41, in <dictcomp>
    reader: readers[reader].get_meta(
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/components/interfaces.py", line 47, in get_meta
    "config": {_c: self.config[_c].model_dump() for _c in self.config},
  File "/home/dev/.local/lib/python3.10/site-packages/goldenverba/components/interfaces.py", line 47, in <dictcomp>
    "config": {_c: self.config[_c].model_dump() for _c in self.config},
AttributeError: 'InputText' object has no attribute 'model_dump'
/usr/lib/python3.10/tempfile.py:999: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpfrnxdxoq'>
  _warnings.warn(warn_message, ResourceWarning)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
{"action":"restapi_management","level":"info","msg":"Shutting down... ","time":"2024-05-23T10:43:41+01:00"}
{"action":"restapi_management","level":"info","msg":"Stopped serving weaviate at http://127.0.0.1:6666","time":"2024-05-23T10:43:41+01:00"}
---
Please advise hot to fix?

**Comment by 2532380** [comment]
me2

**Comment by pavlosidelov** [comment]
Thats correct. I have installed it globally not with Venv.
Venv scenario installation makes things work.
In your manual, you just skipped Venv activation and I forgot to do it
All started properly
