### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by coxfrederic** [weaviate/Verba#200]
I followed the instructions and installed pythong 3.10.5
I also created the virtual environment, but I can't start verba. When I google it it seems to refer to an issue of using a python version lower than 3.10 but that's not the case? What am I doing wrong? My python experience is rather limited .. sorry for that.

(appenv) [ec2-user@ip-172-31-35-70 Python-3.10.5]$ verba start
/home/ec2-user/.local/lib/python3.9/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/verba", line 5, in <module>
    from goldenverba.server.cli import cli
  File "/home/ec2-user/.local/lib/python3.9/site-packages/goldenverba/server/cli.py", line 6, in <module>
    from goldenverba.verba_manager import VerbaManager
  File "/home/ec2-user/.local/lib/python3.9/site-packages/goldenverba/verba_manager.py", line 29, in <module>
    class VerbaManager:
  File "/home/ec2-user/.local/lib/python3.9/site-packages/goldenverba/verba_manager.py", line 156, in VerbaManager
    def setup_client(self) -> Client | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(appenv) [ec2-user@ip-172-31-35-70 Python-3.10.5]$

**Comment by thomashacker** [comment]
Looking at the error messages it seems like you're still using `python3.9`, make sure that you use at least `python3.10`
