### ISSUE TITLE
Verba Start fails

### ISSUE THREAD

**Issue by brianjking** [weaviate/Verba#23]
```
 ✘    ~  verba start                                                                                                                           (verba)   10:18   28.09.23 
INFO:     Will watch for changes in these directories: ['/Users/brianjking']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [28438] using WatchFiles
ℹ Setting up client
ℹ VERBA_URL environment variable not set. Using Weaviate Embedded
Started ./.verba/cache/weaviate-embedded: process ID 28442
{"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-09-28T10:19:02-07:00"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-09-28T10:19:02-07:00"}
{"level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2023-09-28T10:19:02-07:00"}
{"action":"grpc_startup","error":"listen tcp :50051: bind: address already in use","level":"fatal","msg":"failed to start grpc server","time":"2023-09-28T10:19:02-07:00"}
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.11/site-packages/goldenverba/server/api.py", line 22, in <module>
    verba_engine = AdvancedVerbaQueryEngine()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/goldenverba/retrieval/interface.py", line 15, in __init__
    VerbaQueryEngine.client = setup_client()
                              ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/goldenverba/ingestion/util.py", line 41, in setup_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/weaviate/client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/weaviate/client.py", line 288, in __parse_url_and_embedded_db
    embedded_db.start()
  File "/opt/homebrew/lib/python3.11/site-packages/weaviate/embedded.py", line 229, in start
    self.wait_till_listening()
  File "/opt/homebrew/lib/python3.11/site-packages/weaviate/embedded.py", line 174, in wait_till_listening
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Embedded DB did not start listening on port 6666 within 30 seconds
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
```

**Comment by brianjking** [comment]
Running lsof -i :50051 doesn't return any open files

**Comment by brianjking** [comment]
any ideas?

**Comment by thomashacker** [comment]
Interesting! Thanks for the issue, we'll look into this

**Comment by thomashacker** [comment]
This issue should be fixed with the new 0.3.0 version 🚀  Thanks a lot!

**Comment by thomashacker** [comment]
Interesting, there might be some issues with the ports the gRPC client tries to access (50051). 

```
{"action":"grpc_startup","error":"listen tcp :50051: bind: address already in use","level":"fatal","msg":"failed to start grpc server","time":"2023-11-21T20:19:18+01:00"}
```

It might be possible that a process is already using that port or it's being blocked?

**Comment by srikanthmalla** [comment]
@thomashacker , I am also getting similar error. Any updates?

Below is the error with latest verba 0.3.1 with either pip install, or install from source:

~/weviate/Verba$ **verba start**
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  warnings.warn(
INFO:     Will watch for changes in these directories: ['/home/user/weviate/Verba']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [366767] using WatchFiles
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  warnings.warn(
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/fastapi/openapi/models.py:55: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
  return general_plain_validator_function(cls._validate)
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/pydantic_core/core_schema.py:3902: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
  warnings.warn(
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:121: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("best_of")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:140: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("repetition_penalty")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:146: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("seed")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:152: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("temperature")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:158: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("top_k")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:164: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("top_p")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:170: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("truncate")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:176: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("typical_p")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:204: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("inputs")
/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:210: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  @validator("stream")
ℹ Setting up client
ℹ Using Weaviate Embedded
embedded weaviate is already listening on port 6666
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/user/.local/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/weaviate/connect/connection.py", line 643, in wait_for_weaviate
    requests.get(ready_url, headers=self._get_request_header()).raise_for_status()
  File "/home/user/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/goldenverba/server/api.py", line 33, in <module>
    manager = verba_manager.VerbaManager()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/goldenverba/verba_manager.py", line 41, in __init__
    self.client = self.setup_client()
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/goldenverba/verba_manager.py", line 217, in setup_client
    client = weaviate.Client(
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/weaviate/connect/connection.py", line 163, in __init__
    self.wait_for_weaviate(startup_period)
  File "/home/user/anaconda3/envs/goldenverba/lib/python3.10/site-packages/weaviate/connect/connection.py", line 646, in wait_for_weaviate
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://localhost:6666 is wrong or Weaviate did not start up in the interval given in 'startup_period'.
/home/user/anaconda3/envs/goldenverba/lib/python3.10/tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpz9ceof70'>
  _warnings.warn(warn_message, ResourceWarning)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>

**Comment by thomashacker** [comment]
Seems like there's also an issue with the Weaviate connection, looks like it's already running on port 6666. Could you try to kill the process on port 6666 and rerun Verba?

**Comment by srikanthmalla** [comment]
Hi @thomashacker , Weviate was not running on port 6666, when I checked nvidia-fabric manager is running on port 6666 by default. I am just following the Readme.md instructions, here: https://github.com/weaviate/Verba?tab=readme-ov-file#%EF%B8%8F-quickstart-build-from-source and here https://github.com/weaviate/Verba?tab=readme-ov-file#%EF%B8%8F-quickstart-build-from-source . Could you provide a solution to adjust the port for weviate and easy start for those who doesn't have any knowledge of weviate. Please let me know.

**Comment by thomashacker** [comment]
Hm that's weird, the logs that you showed here say `embedded weaviate is already listening on port 6666` there must be something weird going on! Could you try to use a free sandbox cluster on https://console.weaviate.cloud/ and see if it works when you use a cluster?

**Comment by thomashacker** [comment]
Ah, nice catch, thanks a lot! Let me know if the error persists, I'll close this for now

**Comment by michaelmior** [comment]
I'm seeing a similar issue on my MacBook Pro with M3 Max. Nothing listening on port 6666.

```
$ verba start
verba start                                                                                                                                                                                                        07:27:39
INFO:     Will watch for changes in these directories: ['/Users/mjmvcs/verba']
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [65838] using WatchFiles
ℹ Setting up client
ℹ Using Weaviate Embedded
Started /Users/mjmvcs/.cache/weaviate-embedded: process ID 65841
{"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2
024-05-21T07:27:42-04:00"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-05-21T07:27:42-04:00"}
{"action":"memberlist_init","bind_port":65139,"error":"Failed to get final advertise address: No private IP address found, and explicit IP not provided","hostname":"Embedded_at_6666","level":"error","msg":"memberlist not created","time":"
2024-05-21T07:27:42-04:00"}
{"action":"startup","error":"create member list: Failed to get final advertise address: No private IP address found, and explicit IP not provided","level":"error","msg":"could not init cluster state","time":"2024-05-21T07:27:42-04:00"}
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/goldenverba/server/api.py", line 37, in <module>
    manager = verba_manager.VerbaManager()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/goldenverba/verba_manager.py", line 45, in __init__
    self.client = self.setup_client()
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/goldenverba/verba_manager.py", line 209, in setup_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/weaviate/client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/weaviate/client.py", line 288, in __parse_url_and_embedded_db
    embedded_db.start()
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/weaviate/embedded.py", line 223, in start
    self.wait_till_listening()
  File "/Users/mjmvcs/Library/Application Support/pipx/venvs/goldenverba/lib/python3.12/site-packages/weaviate/embedded.py", line 168, in wait_till_listening
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Embedded DB did not start listening on port 6666 within 30 seconds
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
```

**Comment by thomashacker** [comment]
Thanks for the issue. This is interesting:

```bash
{"action":"memberlist_init","bind_port":65139,"error":"Failed to get final advertise address: No private IP address found, and explicit IP not provided","hostname":"Embedded_at_6666","level":"error","msg":"memberlist not created","time":"
2024-05-21T07:27:42-04:00"}
```

This seems to be an error with Weaviate Embedded itself, I would recommend posting your issue on our Weaviate Support Forum (https://forum.weaviate.io/) since this error might be interesting for other users with the same issue as well 🚀 

If Weaviate Embedded doesn't work for now, you can either use the Docker Deployment or WCS Sandbox Cluster  as workaround.
