### ISSUE TITLE
Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

### ISSUE THREAD

**Issue by ecorpnu** [weaviate/Verba#233]
## Description
Windows not supported 

## Is this a bug or a feature?
- [ ] Bug
- [ ] Feature

## Steps to Reproduce

verba start (running in virtualenv)

(venv) C:\verba>verba start
←[32mINFO←[0m:     Will watch for changes in these directories: ['C:\\verba']
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://localhost:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     Started reloader process [←[36m←[1m24896←[0m] using ←[36m←[1mWatchFiles←[0m
ℹ Setting up client
ℹ Using Weaviate Embedded
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\verba\venv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\verba\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\verba\venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\verba\venv\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\verba\venv\Lib\site-packages\goldenverba\server\api.py", line 37, in <module>
    manager = verba_manager.VerbaManager()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\goldenverba\verba_manager.py", line 45, in __init__
    self.client = self.setup_client()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\goldenverba\verba_manager.py", line 209, in setup_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\weaviate\client.py", line 147, in __init__
    url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\weaviate\client.py", line 287, in __parse_url_and_embedded_db
    embedded_db = EmbeddedDB(options=embedded_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\verba\venv\Lib\site-packages\weaviate\embedded.py", line 52, in __init__
    self.check_supported_platform()
  File "C:\verba\venv\Lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by thomashacker** [comment]
You can install Verba via WSL as a workaround. Weaviate Embedded for Windows is on the road map and will be added to Verba as soon as the update arrives 🚀
