### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by cometothed4rkside** [weaviate/Verba#24]
ℹ Setting up client
✔ Client connected to Weaviate Cluster
ℹ All schemas available
ℹ Reading data\minecraft\minecraft_guide.txt
ℹ Reading data\minecraft\minecraft_wiki.txt
✔ Loaded 2 files
ℹ Converted data\minecraft\minecraft_guide.txt
Traceback (most recent call last):
  File "\\?\C:\Users\xxxx\AppData\Local\Programs\Python\Python310\Scripts\verba-script.py", line 33, in <module>
    sys.exit(load_entry_point('goldenverba', 'console_scripts', 'verba')())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\xxxx\desktop\train\verba\goldenverba\ingestion\cli.py", line 68, in import_data_command
    import_data(path, model)
  File "c:\users\xxxx\desktop\train\verba\goldenverba\ingestion\import_data.py", line 65, in import_data
    documents = convert_files(client, file_contents, nlp=nlp)
  File "c:\users\xxxx\desktop\train\verba\goldenverba\ingestion\preprocess.py", line 178, in convert_files
    if not check_if_file_exits(client, file_name):
  File "c:\users\xxxx\desktop\train\verba\goldenverba\ingestion\preprocess.py", line 207, in check_if_file_exits
    if results["data"]["Get"]["Document"]:
KeyError: 'data'

C:\Users\xxxx\Desktop\train\Verba>

**Comment by thomashacker** [comment]
Thanks, we'll look into that!

**Comment by thomashacker** [comment]
This issue should be fixed with the new 0.3.0 version 🚀  Thanks a lot!
