### ISSUE TITLE
Windows is not supported with EmbeddedDB. plz give solution for it because its not working even after WCS implementation 

### ISSUE THREAD

**Issue by ahsan0444** [weaviate/Verba#246]
I'm encountering an error when trying to run Weaviate with the EmbeddedDB option on a Windows system. The error message indicates that Windows is not currently supported for this functionality.
i have created a environment
installed all the requirements
then setup a llama 3 model
after that when i am starting the verba, i am facing the issue of embeddingDB,

INFO: Will watch for changes in these directories: ['D:\projects\Verba Project\Verba']
INFO: Uvicorn running on http://localhost:8000/ (Press CTRL+C to quit)
INFO: Started reloader process [12028] using WatchFiles
lora
barwa
ℹ Setting up client
ℹ Using Weaviate Embedded
Process SpawnProcess-1:
Traceback (most recent call last):
File "C:\Users\User\anaconda3\envs\envmenv\Lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\User\anaconda3\envs\envmenv\Lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn_subprocess.py", line 78, in subprocess_started
target(sockets=sockets)
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 65, in run
return asyncio.run(self.serve(sockets=sockets))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\asyncio\base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 69, in serve
await self._serve(sockets)
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\server.py", line 76, in serve
config.load()
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\config.py", line 433, in load
self.loaded_app = import_from_string(self.app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
module = importlib.import_module(module_str)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\importlib_init.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1387, in _gcd_import
File "", line 1360, in _find_and_load
File "", line 1331, in _find_and_load_unlocked
File "", line 935, in _load_unlocked
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "d:\projects\verba project\verba\goldenverba\server\api.py", line 37, in
manager = verba_manager.VerbaManager()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 45, in init
self.client = self.setup_client()
^^^^^^^^^^^^^^^^^^^
File "d:\projects\verba project\verba\goldenverba\verba_manager.py", line 209, in setup_client
client = weaviate.Client(
^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\client.py", line 147, in init
url, embedded_db = self.__parse_url_and_embedded_db(url, embedded_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\client.py", line 287, in __parse_url_and_embedded_db
embedded_db = EmbeddedDB(options=embedded_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\embedded.py", line 52, in init
self.check_supported_platform()
File "C:\Users\User\anaconda3\envs\envmenv\Lib\site-packages\weaviate\embedded.py", line 175, in check_supported_platform
raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by thomashacker** [comment]
If you created a cluster in Weaviate Cloud, you need to set both `WEAVIATE_URL_VERBA` and `WEAVIATE_API_KEY_VERBA` in your `.env` file. Another Workaround is `Docker` or `WSL`

**Comment by bziomek** [comment]
It looks like you're not configuring Verba to find your cloud cluster--do as thomashacker says.

This really should be documented in the main Git page though, tbh. Also odd that the example .env is not in the package and is oddly uncommented by default.
