### ISSUE TITLE
Cannot run latest version locally

### ISSUE THREAD

**Issue by jaydcrowe1989** [weaviate/Verba#290]
## Description

I have pulled the latest version and I am trying to deploy it locally using docker and I cannot get it work. It just keeps crashing and shutting down. The logs are showing:

2024-09-23 11:24:58 /usr/local/lib/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at grpc_health/v1/health.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
2024-09-23 11:24:58   warnings.warn(
2024-09-23 11:25:01 Traceback (most recent call last):
2024-09-23 11:25:01   File "/usr/local/bin/verba", line 33, in <module>
2024-09-23 11:25:01     sys.exit(load_entry_point('goldenverba', 'console_scripts', 'verba')())
2024-09-23 11:25:01              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 11:25:01   File "/usr/local/bin/verba", line 25, in importlib_load_entry_point
2024-09-23 11:25:01     return next(matches).load()
2024-09-23 11:25:01            ^^^^^^^^^^^^^^^^^^^^
2024-09-23 11:25:01   File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
2024-09-23 11:25:01     module = import_module(match.group('module'))
2024-09-23 11:25:01              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 11:25:01   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-09-23 11:25:01     return _bootstrap._gcd_import(name[level:], package, level)
2024-09-23 11:25:01            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 11:25:01   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-09-23 11:25:01   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-09-23 11:25:01   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-09-23 11:25:01   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-09-23 11:25:01   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-09-23 11:25:01   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-09-23 11:25:01   File "/Verba/goldenverba/server/cli.py", line 6, in <module>
2024-09-23 11:25:01     from goldenverba import verba_manager
2024-09-23 11:25:01   File "/Verba/goldenverba/verba_manager.py", line 24, in <module>
2024-09-23 11:25:01     from goldenverba.components.managers import (
2024-09-23 11:25:01   File "/Verba/goldenverba/components/managers.py", line 101, in <module>
2024-09-23 11:25:01     CohereEmbedder(),
2024-09-23 11:25:01     ^^^^^^^^^^^^^^^^
2024-09-23 11:25:01   File "/Verba/goldenverba/components/embedding/CohereEmbedder.py", line 27, in __init__
2024-09-23 11:25:01     value=models[0],
2024-09-23 11:25:01           ~~~~~~^^^
2024-09-23 11:25:01 TypeError: 'NoneType' object is not subscriptable
2024-09-23 11:25:01 ℹ Couldn't connect to Ollama http://localhost:11434

I suspect this is failing because it is trying to connect to Ollama but I want to connect to OPENAI which I have set the api key for in the .env file.

## Installation

- [ ] pip install goldenverba
- [ ] pip install from source
- [X ] Docker installation

If you installed via pip, please specify the version:

## Weaviate Deployment

- [ X] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

**Comment by jaydcrowe1989** [comment]
Any news on this issue?

**Comment by MikeG27** [comment]
Have the same issue. Any news?

**Comment by jaydcrowe1989** [comment]
Thank you very much @tz1112 that has solved my issues!!
