### ISSUE TITLE
requests.exceptions.ReadTimeout: The 'objects' creation was cancelled because it took longer than the configured timeout of 60s. Try reducing the batch size (currently 1550) to a lower value. Aim to on average complete batch request within less than 10s

### ISSUE THREAD

**Issue by huynq55** [weaviate/Verba#33]
ℹ (1549/6283) Importing chunk of /home/huy/sutta3/mn122.txt (7)
ℹ (1550/6283) Importing chunk of /home/huy/sutta3/mn122.txt (8)
[ERROR] Batch ReadTimeout Exception occurred! Retrying in 2s. [1/3]
[ERROR] Batch ReadTimeout Exception occurred! Retrying in 4s. [2/3]
[ERROR] Batch ReadTimeout Exception occurred! Retrying in 6s. [3/3]
Traceback (most recent call last):
  File "/home/huy/miniconda3/envs/verba/bin/verba", line 33, in <module>
    sys.exit(load_entry_point('goldenverba', 'console_scripts', 'verba')())
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/huy/Verba/goldenverba/ingestion/cli.py", line 68, in import_data_command
    import_data(path, model)
  File "/home/huy/Verba/goldenverba/ingestion/import_data.py", line 69, in import_data
    import_chunks(client=client, chunks=chunks, doc_uuid_map=uuid_map)
  File "/home/huy/Verba/goldenverba/ingestion/util.py", line 123, in import_chunks
    with client.batch as batch:
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1646, in __exit__
    self.flush()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1252, in flush
    self._send_batch_requests(force_wait=True)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1151, in _send_batch_requests
    response_objects, nr_objects = done_future.result()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/huy/Verba/goldenverba/ingestion/util.py", line 141, in import_chunks
    client.batch.add_data_object(properties, "Chunk")
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 569, in add_data_object
    self._auto_create()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1242, in _auto_create
    self._send_batch_requests(force_wait=False)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1151, in _send_batch_requests
    response_objects, nr_objects = done_future.result()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 1099, in _flush_in_thread
    response = self._create_data(
  File "/home/huy/miniconda3/envs/verba/lib/python3.10/site-packages/weaviate/batch/crud_batch.py", line 750, in _create_data
    raise ReadTimeout(message) from None
requests.exceptions.ReadTimeout: The 'objects' creation was cancelled because it took longer than the configured timeout of 60s. Try reducing the batch size (currently 1550) to a lower value. Aim to on average complete batch request within less than 10s

Import stopped at chunk number 1550. How can I fix this?
Thank for nice app :D

**Comment by thomashacker** [comment]
This issue should be fixed with the new 0.3.0 version 🚀  Thanks a lot!
