### ISSUE TITLE
Add Document button does not work

### ISSUE THREAD

**Issue by AntonioDiTuri** [weaviate/Verba#73]
I have used a virtual environment using virtualenv and Python 3.9.18

I just reproduced the steps from the readme, to reproduce:

```
python3 -m virtual verba
source verba/bin/activate
pip install goldenverba
```

Then I visit localhost:8000 and try to add a document: 

On terminal this is the error I get: 
```
Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.9/site-packages/goldenverba/server/api.py", line 297, in get_components
    config_manager.get_chunker(), chunker[config_manager.get_chunker()]
KeyError: ''
```

This is the UI I see:

![Screenshot 2023-11-30 at 10 31 10](https://github.com/weaviate/Verba/assets/43536425/56e42e03-2347-4c4c-bf3a-211c2798a03a)

I have also tried to install torch but nothing changed. 
I will also try other python version but wanted to let you guys know!

**Comment by JannikSchneider12** [comment]
Did someone solve the problem? I am always getting this error, no matter which python version I use

**Comment by isabelline** [comment]
In my case, when I added the ip addess at origins in Verba/goldenverba/server/api.py, it worked

origins = [
    "http://localhost:3000",
    "https://verba-golden-ragtriever.onrender.com",
    "http://localhost:8000",
    "http://{myip}:8000",
]

**Comment by thomashacker** [comment]
Interesting! Thanks for the issue
We look into that 🚀

**Comment by rosersauri** [comment]
I solved the problem by making sure I had all the required libraries installed in the virtual environment, running:

`pip install -r requirements.txt`

In my case, I was missing torch. transformers, and accelerate.

**Comment by thomashacker** [comment]
The newest release should fix this issue! Let me know if it persists
